/*
 * File: WinAdd.ui.js
 * Date: Fri Mar 04 2011 15:01:56 GMT+0900 (JST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

WinAddUi = Ext.extend(Ext.Window, {
    title: 'データ追加',
    width: 400,
    height: 177,
    layout: 'form',
    padding: 10,
    modal: true,
    initComponent: function() {
        this.fbar = {
            xtype: 'toolbar',
            ref: 'tbAdd',
            id: 'tbAdd',
            items: [
                {
                    id: 'btnAddOK',
                    ref: '../btnAddOK',
                    xtype: 'button',
                    text: 'OK'
                },
                {
                    id: 'btnAddCancel',
                    ref: '../btnAddCancel',
                    xtype: 'button',
                    text: 'キャンセル'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: '氏名',
                anchor: '100%',
                id: 'txtNameKanji',
                ref: 'txtNameKanji'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'フリガナ',
                anchor: '100%',
                ref: 'txtNameKana',
                id: 'txtNameKana'
            },
            {
                xtype: 'datefield',
                fieldLabel: '生年月日',
                anchor: '100%',
                ref: 'txtBirthDate',
                id: 'txtBirthDate'
            }
        ];
        WinAddUi.superclass.initComponent.call(this);
    }
});
