/*
 * File: WinMain.ui.js
 * Date: Fri Mar 04 2011 13:02:43 GMT+0900 (JST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

WinMainUi = Ext.extend(Ext.Window, {
    title: '従業員',
    width: 700,
    height: 300,
    layout: 'fit',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            ref: 'tbMain',
            id: 'tbMain',
            items: [
                {
                    xtype: 'button',
                    text: '保存',
                    id: 'btnMainSave',
                    ref: '../btnMainSave'
                },
                {
                    xtype: 'button',
                    text: '追加...',
                    id: 'btnMainAdd',
                    ref: '../btnMainAdd'
                },
                {
                    xtype: 'button',
                    text: '削除',
                    id: 'btnMainDelete',
                    ref: '../btnMainDelete'
                }
            ]
        };
        this.items = [
            {
                xtype: 'editorgrid',
                store: 'EmployeeStore',
                id: 'grdEmployee',
                ref: 'grdEmployee',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'name_kanji',
                        header: '氏名',
                        sortable: false,
                        width: 200,
                        editor: {
                            xtype: 'textfield'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'name_kana',
                        header: 'フリガナ',
                        sortable: false,
                        width: 200,
                        editor: {
                            xtype: 'textfield'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'birth_date',
                        header: '生年月日',
                        sortable: false,
                        width: 200,
                        editor: {
                            xtype: 'datefield'
                        }
                    }
                ]
            }
        ];
        WinMainUi.superclass.initComponent.call(this);
    }
});
