/*
 * File: xds_index.js
 * Date: Fri Mar 04 2011 13:02:43 GMT+0900 (JST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new WinMain({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
